// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiPA_hrY5rMRGJKdPMIb1kSjTWYdetWMU',
    appId: '1:986634165372:web:0fef85a7ce6b929c36bdf9',
    messagingSenderId: '986634165372',
    projectId: 'car-rental-app-flutter-bloc',
    authDomain: 'car-rental-app-flutter-bloc.firebaseapp.com',
    storageBucket: 'car-rental-app-flutter-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoiNedeLix-6I_GjI7el7u-aw_aQOOOzY',
    appId: '1:986634165372:android:3d7ff7b4bbf72fac36bdf9',
    messagingSenderId: '986634165372',
    projectId: 'car-rental-app-flutter-bloc',
    storageBucket: 'car-rental-app-flutter-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP5c-vdRo8hx7ZWhm1f7vE_54C6ejBp2A',
    appId: '1:986634165372:ios:3fc2f756869decf136bdf9',
    messagingSenderId: '986634165372',
    projectId: 'car-rental-app-flutter-bloc',
    storageBucket: 'car-rental-app-flutter-bloc.appspot.com',
    iosBundleId: 'com.example.carRentalAppFlutterBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP5c-vdRo8hx7ZWhm1f7vE_54C6ejBp2A',
    appId: '1:986634165372:ios:3fc2f756869decf136bdf9',
    messagingSenderId: '986634165372',
    projectId: 'car-rental-app-flutter-bloc',
    storageBucket: 'car-rental-app-flutter-bloc.appspot.com',
    iosBundleId: 'com.example.carRentalAppFlutterBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiPA_hrY5rMRGJKdPMIb1kSjTWYdetWMU',
    appId: '1:986634165372:web:46e15c43d9a47c9136bdf9',
    messagingSenderId: '986634165372',
    projectId: 'car-rental-app-flutter-bloc',
    authDomain: 'car-rental-app-flutter-bloc.firebaseapp.com',
    storageBucket: 'car-rental-app-flutter-bloc.appspot.com',
  );

}